= Button Stylers

include::../common.adoc[]

== Overview

This document provides a list of buttion stylers that can be used to style
buttons in the Elements Library. The button stylers are used to define the
appearance of buttons, such as colors, borders, icons and labels, and shapes.
The button stylers are separate from the button classes, which handle user
interactions. This separation of responsibilities allows for greater
flexibility in defining the button's appearance and behavior.

=== Notation

`label`                 :: An object of type std::string.
`bst`                   :: A button styler instance.
`size`                  :: The button's relative size of type `float`.
`color`                 :: An object of type `color`.
`icon_id`               :: Unicode code point of type `std::uint32_t` from the
                           {Global-theme} `icon_font`.
`margin`                :: The margin in pixels of type `rect`.
`r`                     :: The corner radius in pixels of type`float`.
`tl`, `tr`, `bl`, `br`  :: The corner radius in pixels for top-left, top-right,
                           bottom-left, and bottom-right corners of type `float`.




=== Expressions

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
button_styler{label}
----
a|
* Create a button with the given label.

a|
[source,c++]
----
bst.size(size)
----
a|
* Sets the relative size of the button.
* `size` is relative to the default size dictated by the
  {Global-theme}'s `label_font`.
* A value greater than 1.0 makes the button larger.
* A value less than 1.0 makes the button smaller.
a|
[source,c++]
----
bst.color(color)
----
a|
* Sets the color of the button.

a|
[source,c++]
----
bst.active_body_color(color)
----
a|
* Sets the active body color of the button.

a|
[source,c++]
----
bst.text_color(color)
----
a|
* Sets the text color of the button.

a|
[source,c++]
----
bst.icon(icon_id)
----
a|
* Sets the icon of the button.

a|
[source,c++]
----
bst.icon_left()
----
a|
* Sets the icon to the left of the text.

a|
[source,c++]
----
bst.icon_right()
----
a|
* Sets the icon to the right of the text.

a|
[source,c++]
----
bst.icon_color(color)
----
a|
* Sets the icon color of the button.

a|
[source,c++]
----
bst.align_left()
----
a|
* Aligns the text and icon to the left.

a|
[source,c++]
----
bst.align_center()
----
a|
* Aligns the text and icon to the center.

a|
[source,c++]
----
bst.align_right()
----
a|
* Aligns the text and icon to the right.

a|
[source,c++]
----
bst.margin(margin)
----
a|
* Sets the margin of the button.

a|
[source,c++]
----
bst.corner_radius(r)
----
a|
* Sets the corner radius of the button.

a|
[source,c++]
----
bts.corner_radius(tl, tr, bl, br)
----
a|
* Sets the corner radius of the button for each corner.

a|
[source,c++]
----
bts.rounded_top()
----
a|
* Sets the top corners of the button to be rounded.

a|
[source,c++]
----
bts.rounded_bottom()
----
a|
* Sets the bottom corners of the button to be rounded.

a|
[source,c++]
----
bts.rounded_left()
----
a|
* Sets the left corners of the button to be rounded.

a|
[source,c++]
----
bts.rounded_right()
----
a|
* Sets the right corners of the button to be rounded.

a|
[source,c++]
----
bts.rounded_top(r)
----
a|
* Sets the top corners of the button to be rounded with a specific
  radius.

a|
[source,c++]
----
bts.rounded_bottom(r)
----
a|
* Sets the bottom corners of the button to be rounded with a specific
  radius.

a|
[source,c++]
----
bts.rounded_left(r)
----
a|
* Sets the left corners of the button to be rounded with a specific
  radius.

a|
[source,c++]
----
bts.rounded_right(r)
----
a|
* Sets the right corners of the button to be rounded with a specific
  radius.

a|
[source,c++]
----
bts.rounded_corner_top_left(r)
----
a|
* Sets the top-left corner of the button to be rounded with a specific
  radius.

a|
[source,c++]
----
bts.rounded_corner_top_right(r)
----
a|
* Sets the top-right corner of the button to be rounded with a specific
  radius.

a|
[source,c++]
----
bts.rounded_corner_bottom_left(r)
----
a|
* Sets the bottom-left corner of the button to be rounded with a
  specific radius.

a|
[source,c++]
----
bts.rounded_corner_bottom_right(r)
----
a|
* Sets the bottom-right corner of the button to be rounded with a
  specific radius.
|===

All of these expressions return the button styler. Therefore, these expressions
can be chained together to create the button styler with the desired
appearance. The result is then passed to one of the button creation functions
(see {Buttons}).

=== Examples

Make a default momentary button with label "My Button":

[,c++]
----
auto btn = momentary_button(
      button_styler{"My Button"}
   );
----

Make a blue momentary button with label "Lock":

[,c++]
----
auto btn = momentary_button(
      button_styler{"Lock"}
         .body_color(colors::blue)
   );
----

Make a momentary button with label "Rounded Left" and a `left_circled` icon,
aligned to the left, with a rounded left corner of 10 pixels:

[,c++]
----
auto btn = momentary_button(
      button_styler{"Rounded Left"}
         .align_left()
         .icon(icons::left_circled)
         .icon_left()
         .rounded_left(10)
   );
----

== Default Button Styler

The basic button styler is a simple button with a text label with no icon,
with these defaults:

[cols="2,3", options="header"]
|===
| Property                      | Default Value

| size                          | `1.0f`
| body_color                    | {Global-theme} `default_button_color`
| active_body_color             | `body_color`
| text_color                    | {Global-theme} `label_font_color`
| icon                          | `0`
| icon_placement                | `icon_none`
| icon_color                    | {Global-theme} `label_font_color`
| label_alignment               | `align_center`
| margin                        | {Global-theme} `button_margin`
| corner_radius                 | {Global-theme} `button_corner_radius`
| corner_radius_top_left        | `corner_radius`
| corner_radius_top_right       | `corner_radius`
| corner_radius_bottom_left     | `corner_radius`
| corner_radius_bottom_right    | `corner_radius`
|===

== Convenience Functions

The following convenience functions are provided to create commonly used
buttons. These functions simplify button creation, allowing users to quickly
implement standard button types with minimal effort.

=== Notation

`label`                 :: An object of type std::string.
`bst`                   :: A button styler instance.
`size`                  :: The button's relative size of type `float`.
`color`                 :: An object of type `color`.
`icon_id`               :: Unicode code point of type `std::uint32_t` from the

`MBase`                 :: Type that conforms to the MomentaryButton concept.
`TBase`                 :: Type that conforms to the ToggleButton concept.
`LBase`                 :: Type that conforms to the LatchingButton concept.

`[, ...]`               :: Optional parameters.

=== Expressions

==== Momentary buttons

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
button(label
   [, size, color]
)
----
a|
* Creates a button with the specified label, with optional size, and color.

a|
[source,c++]
----
button<MBase>(
   label
   [, size, color]
)
----
a|
* Creates a button with the specified label,, with optional size, and color,
  using the MBase template.
|===

==== Momentary Buttons with Icon to the Left

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
button(
   icon_id, label, size
   [, color]
)
----
a|
* Creates a momentary button with the specified icon to the left, label,
  size, and optional color.

a|
[source,c++]
----
button<MBase>(
   icon_id, label, size
   [, color]
)
----
a|
* Creates a momentary button with the specified icon to the left, label,
  size, and optional color, using the MBase template.
|===

==== Momentary Buttons with Icon to the Right

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
button(
   label, icon_id, size
   [, color]
)
----
a|
* Creates a momentary button with the specified label, icon to the right, size, and optional color.

a|
[source,c++]
----
button<MBase>(
   label, icon_id, size
   [, color]
)
----
a|
* Creates a momentary button with the specified label, icon to the right, size, and optional color, using the MBase template.
|===

==== Toggle Buttons

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
toggle_button(
   label
   [, size, color]
)
----
a|
* Creates a toggle button with the specified label, with optional size, and
  color.

a|
[source,c++]
----
toggle_button<TBase>(
   label
   [, size, color]
)
----
a|
* Creates a toggle button with the specified label, with optional size, and
  color, using the TBase template.
|===

==== Toggle Buttons with Icon to the Left

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
toggle_button(
   icon_id, label, size
   [, color]
)
----
a|
* Creates a toggle button with the specified icon to the left, label, size,
  and optional color.

a|
[source,c++]
----
toggle_button<TBase>(
   icon_id, label
   [, size, color]
)
----
a|
* Creates a toggle button with the specified icon to the left, label, size,
  and optional color, using the TBase template.
|===

==== Toggle Buttons with Icon to the Right

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
toggle_button(
   label, icon_id, size
   [, color]
)
----
a|
* Creates a toggle button with the specified label, icon to the right, size,
  and optional color.

a|
[source,c++]
----
toggle_button<TBase>(
   label, icon_id, size
   [, color]
)
----
a|
* Creates a toggle button with the specified label, icon to the right, size,
  and optional color, using the TBase template.
|===

==== Latching Buttons

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
latching_button(
   label
   [, size, color]
)
----
a|
* Creates a latching button with the specified label, with optional size, and
  color.

a|
[source,c++]
----
latching_button<LBase>(
   label
   [, size, color]
)
----
a|
* Creates a latching button with the specified label, with optional size, and
  color, using the LBase template.
|===

==== Latching Buttons with Icon to the Left

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
latching_button(
   icon_id, label, size
   [, color]
)
----
a|
* Creates a latching button with the specified icon to the left, label, size,
  and optional color.

a|
[source,c++]
----
latching_button<LBase>(
   icon_id, label, size
   [, color]
)
----
a|
* Creates a latching button with the specified icon to the left, label, size,
  and optional color, using the LBase template.
|===

==== Latching Buttons with Icon to the Right

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
latching_button(
   label, icon_id, size
   [, color]
)
----
a|
* Creates a latching button with the specified label, icon to the right,
  size, and optional color.

a|
[source,c++]
----
latching_button<LBase>(
   label, icon_id, size
   [, color]
)
----
a|
* Creates a latching button with the specified label, icon to the right,
  size, and optional color, using the LBase template.
|===

These are forwarding shortcuts to the `button_styler` expressions. They
create a button styler with the specified properties and pass it to the
corresponding button creation function.

Example:

[source,c++]
----
////////////////////////////////////////////////////////////////////////////
// Make a momentary button with label
////////////////////////////////////////////////////////////////////////////
template <concepts::MomentaryButton Base = basic_button>
inline auto button(
   std::string label
 , float size = 1.0
 , color body_color = get_theme().default_button_color)
{
   return momentary_button<Base>(
      button_styler{std::move(label)}
         .size(size)
         .body_color(body_color)
   );
}
----
