= Button Stylers

include::../common.adoc[]

== Overview

This document provides a list of button stylers that can be used to style
buttons in the Elements Library. The button stylers are used to define the
appearance of buttons, such as colors, borders, icons and labels, and shapes.
The button stylers are separate from the button classes, which handle user
interactions. This separation of responsibilities allows for greater
flexibility in defining the button's appearance and behavior.

=== Notation

`label`                 :: An object of type std::string.
`bst`                   :: A button styler instance.
`size`                  :: The button's relative size of type `float`.
`color`                 :: An object of type `{color}`.
`icon_id`               :: Unicode code point of type `std::uint32_t` from the
                           {Global-theme} `icon_font`.
`margin`                :: The margin in pixels of type `rect`.
`r`                     :: The corner radius in pixels of type`float`.
`tl`, `tr`, `bl`, `br`  :: The corner radius in pixels for top-left, top-right,
                           bottom-left, and bottom-right corners of type `float`.

=== Expressions

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
button_styler{label}
----
a|
* Create a button styler with the given label.

a|
[source,c++]
----
bst.size(size)
----
a|
* Sets the relative size of the button.
* `size` is relative to the default size dictated by the
  {Global-theme}'s `label_font`.
* A value greater than 1.0 makes the button larger.
* A value less than 1.0 makes the button smaller.
* Adds a size property to the styler.
a|
[source,c++]
----
bst.color(color)
----
a|
* Sets the color of the button.

a|
[source,c++]
----
bst.active_body_color(color)
----
a|
* Sets the active body color of the button.
* Adds an active body color property to the styler.

a|
[source,c++]
----
bst.text_color(color)
----
a|
* Sets the text color of the button.
* Adds a text color property to the styler.

a|
[source,c++]
----
bst.icon(icon_id)
----
a|
* Sets the icon of the button.
* Adds an icon property to the styler.

a|
[source,c++]
----
bst.icon_left()
----
a|
* Sets the icon to the left of the text.
* Adds an icon placement property to the styler.

a|
[source,c++]
----
bst.icon_right()
----
a|
* Sets the icon to the right of the text.
* Adds an icon placement property to the styler.

a|
[source,c++]
----
bst.icon_color(color)
----
a|
* Sets the icon color of the button.
* Adds an icon color property to the styler.

a|
[source,c++]
----
bst.align_left()
----
a|
* Aligns the text and icon to the left.
* Adds a label alignment property to the styler.

a|
[source,c++]
----
bst.align_center()
----
a|
* Aligns the text and icon to the center.
* Adds a label alignment property to the styler.

a|
[source,c++]
----
bst.align_right()
----
a|
* Aligns the text and icon to the right.
* Adds a label alignment property to the styler.

a|
[source,c++]
----
bst.margin(margin)
----
a|
* Sets the margin of the button.
* Adds a margin property to the styler.

a|
[source,c++]
----
bst.corner_radius(r)
----
a|
* Sets the corner radius of the button.
* Adds a corner radius property to the styler.

a|
[source,c++]
----
bts.corner_radius(tl, tr, bl, br)
----
a|
* Sets the corner radius of the button for each corner.
* Adds individual corner radius properties to the styler.

a|
[source,c++]
----
bts.rounded_top()
----
a|
* Sets the top corners of the button to be rounded with the default
  radius.

a|
[source,c++]
----
bts.rounded_bottom()
----
a|
* Sets the bottom corners of the button to be rounded with the default
  radius.

a|
[source,c++]
----
bts.rounded_left()
----
a|
* Sets the left corners of the button to be rounded with the default
  radius.

a|
[source,c++]
----
bts.rounded_right()
----
a|
* Sets the right corners of the button to be rounded with the default
  radius.

a|
[source,c++]
----
bts.rounded_top(r)
----
a|
* Sets the top corners of the button to be rounded with a specific
  radius.
* Adds top-left and top-right corner radius properties to the styler.

a|
[source,c++]
----
bts.rounded_bottom(r)
----
a|
* Sets the bottom corners of the button to be rounded with a specific
  radius.
* Adds bottom-left and bottom-right corner radius properties to the styler.

a|
[source,c++]
----
bts.rounded_left(r)
----
a|
* Sets the left corners of the button to be rounded with a specific
  radius.
* Adds top-left and bottom-left corner radius properties to the styler.

a|
[source,c++]
----
bts.rounded_right(r)
----
a|
* Sets the right corners of the button to be rounded with a specific
  radius.
* Adds top-right and bottom-right corner radius properties to the styler.

a|
[source,c++]
----
bts.rounded_corner_top_left(r)
----
a|
* Sets the top-left corner of the button to be rounded with a specific
  radius.
* Adds top-left corner radius property to the styler.

a|
[source,c++]
----
bts.rounded_corner_top_right(r)
----
a|
* Sets the top-right corner of the button to be rounded with a specific
  radius.
* Adds top-right corner radius property to the styler.

a|
[source,c++]
----
bts.rounded_corner_bottom_left(r)
----
a|
* Sets the bottom-left corner of the button to be rounded with a
  specific radius.
* Adds bottom-left corner radius property to the styler.

a|
[source,c++]
----
bts.rounded_corner_bottom_right(r)
----
a|
* Sets the bottom-right corner of the button to be rounded with a
  specific radius.
* Adds bottom-right corner radius property to the styler.
|===

All of these expressions return the button styler. Therefore, these expressions
can be chained together to create the button styler with the desired
appearance. The result is then passed to one of the button creation functions
(see {Buttons}).

=== Examples

Make a default momentary button with label "My Button":

[source,c++]
----
auto btn = momentary_button(
      button_styler{"My Button"}
   );
----

Make a blue momentary button with label "Lock":

[source,c++]
----
auto btn = momentary_button(
      button_styler{"Lock"}
         .body_color(colors::blue)
   );
----

Make a momentary button with label "Rounded Left" and a `left_circled` icon,
aligned to the left, with a rounded left corner of 10 pixels:

[source,c++]
----
auto btn = momentary_button(
      button_styler{"Rounded Left"}
         .align_left()
         .icon(icons::left_circled)
         .icon_left()
         .rounded_left(10)
   );
----

== Button Styler Defaults

The basic button styler is a simple button with a text label with no icon,
with these defaults:

[cols="2,3", options="header"]
|===
| Property                      | Default Value

| size                          | `1.0f`
| body_color                    | {Global-theme} `default_button_color`
| active_body_color             | `body_color`
| text_color                    | {Global-theme} `label_font_color`
| icon                          | `0`
| icon_placement                | `icon_none`
| icon_color                    | {Global-theme} `label_font_color`
| label_alignment               | `align_center`
| margin                        | {Global-theme} `button_margin`
| corner_radius                 | {Global-theme} `button_corner_radius`
| corner_radius_top_left        | `corner_radius`
| corner_radius_top_right       | `corner_radius`
| corner_radius_bottom_left     | `corner_radius`
| corner_radius_bottom_right    | `corner_radius`
|===

== Convenience Functions

The following convenience functions are provided to create commonly used
buttons. These functions simplify button creation, allowing users to quickly
implement standard button types with minimal effort.

=== Notation

`label`                 :: An object of type std::string.
`bst`                   :: A button styler instance.
`size`                  :: The button's relative size of type `float`.
`color`                 :: An object of type `color`.
`icon_id`               :: Unicode code point of type `std::uint32_t` from the

`MBase`                 :: Type that conforms to the MomentaryButton concept.
`TBase`                 :: Type that conforms to the ToggleButton concept.
`LBase`                 :: Type that conforms to the LatchingButton concept.

`[, ...]`               :: Optional parameters.

=== Expressions

==== Momentary buttons

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
button(
   label
   [, size, color]
)
----
a|
* Creates a button with label, and optional size, and color.

a|
[source,c++]
----
button<MBase>(
   label
   [, size, color]
)
----
a|
* Creates a button with label, and optional size, and color,
  using the MBase template.

a|
[source,c++]
----
button(
   icon_id, label, size
   [, color]
)
----
a|
* Creates a momentary button with icon to the left, label,
  size, and optional color.

a|
[source,c++]
----
button<MBase>(
   icon_id, label, size
   [, color]
)
----
a|
* Creates a momentary button with icon to the left, label,
  size, and optional color, using the MBase template.

a|
[source,c++]
----
button(
   label, icon_id, size
   [, color]
)
----
a|
* Creates a momentary button with label, icon to the right, size, and
  optional color.

a|
[source,c++]
----
button<MBase>(
   label, icon_id, size
   [, color]
)
----
a|
* Creates a momentary button with label, icon to the right, size, and
  optional color, using the MBase template.
|===

==== Toggle Buttons

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
toggle_button(
   label
   [, size, color]
)
----
a|
* Creates a toggle button with label, and optional size, and
  color.

a|
[source,c++]
----
toggle_button<TBase>(
   label
   [, size, color]
)
----
a|
* Creates a toggle button with label, and optional size, and
  color, using the TBase template.

a|
[source,c++]
----
toggle_button(
   icon_id, label, size
   [, color]
)
----
a|
* Creates a toggle button with icon to the left, label, size,
  and optional color.

a|
[source,c++]
----
toggle_button<TBase>(
   icon_id, label
   [, size, color]
)
----
a|
* Creates a toggle button with icon to the left, label, size,
  and optional color, using the TBase template.

a|
[source,c++]
----
toggle_button(
   label, icon_id, size
   [, color]
)
----
a|
* Creates a toggle button with label, icon to the right, size,
  and optional color.

a|
[source,c++]
----
toggle_button<TBase>(
   label, icon_id, size
   [, color]
)
----
a|
* Creates a toggle button with label, icon to the right, size,
  and optional color, using the TBase template.
|===

==== Latching Buttons

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
latching_button(
   label
   [, size, color]
)
----
a|
* Creates a latching button with label, and optional size, and
  color.

a|
[source,c++]
----
latching_button<LBase>(
   label
   [, size, color]
)
----
a|
* Creates a latching button with label, and optional size, and
  color, using the LBase template.

a|
[source,c++]
----
latching_button(
   icon_id, label, size
   [, color]
)
----
a|
* Creates a latching button with icon to the left, label, size,
  and optional color.

a|
[source,c++]
----
latching_button<LBase>(
   icon_id, label, size
   [, color]
)
----
a|
* Creates a latching button with icon to the left, label, size,
  and optional color, using the LBase template.

a|
[source,c++]
----
latching_button(
   label, icon_id, size
   [, color]
)
----
a|
* Creates a latching button with label, icon to the right,
  size, and optional color.

a|
[source,c++]
----
latching_button<LBase>(
   label, icon_id, size
   [, color]
)
----
a|
* Creates a latching button with label, icon to the right,
  size, and optional color, using the LBase template.
|===

These are overloaded forwarding functions that create a button styler with
specified properties and pass it to the corresponding button creation
function.

Example:

[source,c++]
----
////////////////////////////////////////////////////////////////////////////
// Make a momentary button with label
////////////////////////////////////////////////////////////////////////////
template <concepts::MomentaryButton Base = basic_button>
inline auto button(
   std::string label
 , float size = 1.0
 , color body_color = get_theme().default_button_color)
{
   return momentary_button<Base>(
      button_styler{std::move(label)}
         .size(size)
         .body_color(body_color)
   );
}
----

== Getters and Setters

The following functions are provided to get and set the properties of a
button styler.

=== Notation

`label`                 :: An object of type std::string.
`bst`                   :: A button styler instance.
`size`                  :: The button's relative size of type `float`.
`color`                 :: An object of type `{color}`.
`icon_id`               :: Unicode code point of type `std::uint32_t` from the
                           {Global-theme} `icon_font`.
`margin`                :: The margin in pixels of type `rect`.
`r`                     :: The corner radius in pixels of type`float`.
`tl`, `tr`, `bl`, `br`  :: The corner radius in pixels for top-left, top-right,
                           bottom-left, and bottom-right corners of type `float`.

=== Expressions

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
bst.set_text(label)
----
a|
* Sets the text of the button.

a|
[source,c++]
----
bst.get_text()
----
a|
* Gets the text of the button.
* Returns `std::string_view`.

a|
[source,c++]
----
bst.get_size()
----
a|
* Gets the size of the button.
* Size is in pixels
* Returns the default if the styler does not have a size property.
* Returns `float`.

a|
[source,c++]
----
bst.set_size(size)
----
a|
* Sets the size of the button.
* Size is in pixels
* Compiler error if the styler does not have a size property.

a|
[source,c++]
----
bst.get_body_color()
----
a|
* Gets the body color of the button.
* Returns the default if the styler does not have a body color property.
* Returns `{color}`.

a|
[source,c++]
----
bst.set_body_color(color)
----
a|
* Sets the body color of the button.
* Compiler error if the styler does not have a body color property.

a|
[source,c++]
----
bst.get_active_body_color()
----
a|
* Gets the active body color of the button.
* Returns the default if the styler does not have an active body color property.
* Returns `{color}`.

a|
[source,c++]
----
bst.set_active_body_color(color)
----
a|
* Sets the active body color of the button.
* Compiler error if the styler does not have an active body color property.

a|
[source,c++]
----
bst.get_text_color()
----
a|
* Gets the text color of the button.
* Returns the default if the styler does not have a text color property.
* Returns `{color}`.
a|
[source,c++]
----
bst.set_text_color(color)
----
a|
* Sets the text color of the button.
* Compiler error if the styler does not have a text color property.

a|
[source,c++]
----
bst.get_icon()
----
a|
* Gets the icon of the button.
* Returns the default if the styler does not have an icon property.
* Returns `std::uint32_t`.
a|
[source,c++]
----
bst.set_icon(icon_id)
----
a|
* Sets the icon of the button.
* Compiler error if the styler does not have an icon property.

a|
[source,c++]
----
bst.get_icon_placement()
----
a|
* Gets the icon placement of the button.
* Returns the default if the styler does not have an icon placement property.
* Returns `icon_placement`.
a|
[source,c++]
----
bst.set_icon_placement(placement)
----
a|
* Sets the icon placement of the button.
* Compiler error if the styler does not have an icon placement property.
a|
[source,c++]
----
bst.icon_left()
----
a|
* Sets the icon to the left of the text.
* Compiler error if the styler does not have an icon placement property.
a|
[source,c++]
----
bst.icon_right()
----
a|
* Sets the icon to the right of the text.
* Compiler error if the styler does not have an icon placement property.

a|
[source,c++]
----
bst.get_icon_color()
----
a|
* Gets the icon color of the button.
* Returns the default if the styler does not have an icon color property.
* Returns `{color}`.
a|
[source,c++]
----
bst.set_icon_color(color)
----
a|
* Sets the icon color of the button.
* Compiler error if the styler does not have an icon color property.

a|
[source,c++]
----
bst.get_label_alignment()
----
a|
* Gets the label alignment of the button.
* Returns the default if the styler does not have a label alignment property.
* Returns `label_alignment`.
a|
[source,c++]
----
bst.set_label_alignment(align)
----
a|
* Sets the label alignment of the button.
* Compiler error if the styler does not have a label alignment property.
a|
[source,c++]
----
bst.align_left()
----
a|
* Aligns the text and icon to the left.
* Compiler error if the styler does not have a label alignment property.
a|
[source,c++]
----
bst.align_center()
----
a|
* Aligns the text and icon to the center.
* Compiler error if the styler does not have a label alignment property.
a|
[source,c++]
----
bst.align_right()
----
a|
* Aligns the text and icon to the right.
* Compiler error if the styler does not have a label alignment property.

a|
[source,c++]
----
bst.get_margin()
----
a|
* Gets the margin of the button.
* Returns the default if the styler does not have a margin property.
* Returns `rect`.
a|
[source,c++]
----
bst.set_margin(margin)
----
a|
* Sets the margin of the button.
* Compiler error if the styler does not have a margin property.

a|
[source,c++]
----
bst.get_corner_radius()
----
a|
* Gets the corner radius of the button.
* Returns the default if the styler does not have a corner radius property.
* Returns `float`.
a|
[source,c++]
----
bst.set_corner_radius(r)
----
a|
* Sets the corner radius of the button.
* Compiler error if the styler does not have a corner radius property.
a|
[source,c++]
----
bst.set_corner_radius(
   tl, tr, bl, br
)
----
a|
* Sets the corner radius of the button for each corner.
* Compiler error if the styler does not have individual corner radius property.

a|
[source,c++]
----
bst.get_corner_radius_top_left()
----
a|
* Gets the top-left corner radius of the button.
* Returns the default if the styler does not have a specific top-left corner radius property.
* Returns `float`.
a|
[source,c++]
----
bst.get_corner_radius_top_right()
----
a|
* Gets the top-right corner radius of the button.
* Returns the default if the styler does not have a specific top-right corner radius property.
* Returns `float`.
a|
[source,c++]
----
bst.get_corner_radius_bottom_left()
----
a|
* Gets the bottom-left corner radius of the button.
* Returns the default if the styler does not have a specific bottom-left corner radius property.
* Returns `float`.
a|
[source,c++]
----
bst.get_corner_radius_bottom_right()
----
a|
* Gets the bottom-right corner radius of the button.
* Returns the default if the styler does not have a specific bottom-right corner radius property.
* Returns `float`.

|===


'''

_Copyright (c) 2014-2024 Joel de Guzman. All rights reserved._
_Distributed under the {mit_license}_
