= Labels

include::../common.adoc[]

== Overview

Labels are used to display static text. They are typically used for various
tasks such as annotating other elements, such as input fields or buttons.
Label stylers allow for the customization of the label's appearance,
including the font, font color, font size, and text alignment.

The `default_label_styler` class is the base class for label stylers. It
provides the default appearance for labels. There are a couple of derived
classes that provide various properties that override the defaults. These
shall remain private to the library.

=== Declaration

[source,c++]
----
class default_label_styler;
----

=== Concepts

[source,c++]
----
namespace concepts
{
   template <typename T>
   concept ButtonStyler = std::is_base_of_v<default_label_styler, std::decay_t<T>>;
}
----

=== Notation

`str`           :: `std::string`
`lst`           :: A label styler instance.
`font`          :: A font descriptor `{font_descr}`.
`size`          :: `float`.
`color`         :: An object of type `{color}`.

=== Expressions

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
label(str)
----

a|
* Create a label styler with the given text.

a|
[source,c++]
----
heading(str)
----

a|
* Create a heading with the given text.

a|
[source,c++]
----
lst.font(font)
----

a|
* Set the font of the label.
* Adds a font property to the label styler.

a|
[source,c++]
----
lst.font_size(size)
----

a|
* Set the font size of the label.
* Adds a font size property to the label styler.

a|
[source,c++]
----
lst.relative_font_size(size)
----

a|
* Set the relative font size of the label.
* `size` is relative to the default size dictated by the
  {Global-theme}'s `label_font`.
* A value greater than 1.0 makes the label larger.
* A value less than 1.0 makes the label smaller.
* Adds a font size property to the label styler.

a|
[source,c++]
----
lst.font_color(color)
----

a|
* Set the font color of the label.
* Adds a font color property to the label styler.

a|
[source,c++]
----
lst.text_align(align)
----

a|
* Set the text alignment of the label. See {text-align} for more info.
* Adds a text alignment property to the label styler.
|===

All of these expressions return the label styler. Therefore, these
expressions can be chained together to create the label styler with the
desired appearance.

=== Example

[source,c++]
----
auto my_label = label("My Label")
   .font(font_descr{"Open Sans"}.semi_bold())
   .font_color(colors::antique_white)
   .font_size(18)
   ;
----

== Enable/Disable

Labels can be either enabled or disabled. When a label is disabled, it will
appear grayed-out, indicating its disabled state.

=== Notation

`lst`    :: A label styler instance.
`state`  :: A boolean value indicating whether the label is enabled or disabled.

=== Expressions

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
lst.enable(state)
----
a|
* Sets the label's enabled state. Pass `true` to the `state` argument to
  enable the label, or `false` to disable it.
a|
[source,c++]
----
lst.is_enabled()
----
a|
* Returns `true` if the label is enabled, `false` otherwise.
|===

== Label Styler Defaults

The default label styler is created with the following defaults:

[cols="2,3", options="header"]
|===
| Property | Default

| font                          | {Global-theme} `label_font`
| font_size                     | {Global-theme} `label_font.size`
| relative_font_size            | `1.0f`
| font_color                    | {Global-theme} `label_font_color`
| text_align                    | {Global-theme} `label_text_align`
|===

== Heading Styler Defaults

The default heading styler is created with the following defaults:

[cols="2,3", options="header"]
|===
| Property | Default

| font                          | {Global-theme} `heading_font`
| font_size                     | {Global-theme} `heading_font.size`
| relative_font_size            | `1.0f`
| font_color                    | {Global-theme} `heading_font_color`
| text_align                    | {Global-theme} `heading_text_align`
|===

== Getters and Setters

The following functions are provided to get and set the properties of a
label styler.

=== Notation

`str`           :: `std::string`
`lst`           :: A label styler instance.
`font`          :: A font descriptor `{font_descr}`.
`size`          :: `float`.
`color`         :: An object of type `{color}`.

=== Expressions

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
lst.get_text()
----
a|
* Get the text of the label.
* Returns `std::string`.
a|
[source,c++]
----
lst.set_text(str)
----
a|
* Set the text of the label.

a|
[source,c++]
----
lst.get_font()
----
a|
* Get the font of the label.
* Returns `{font_descr}`.
* Returns the default if the styler does not have a font property.
a|
[source,c++]
----
lst.set_font(font)
----
a|
* Set the font of the label.
* Compiler error if the styler does not have a font property.

a|
[source,c++]
----
lst.get_font_size()
----
a|
* Get the font size of the label.
* Returns `float`.
* Returns the default if the styler does not have a font size property.
a|
[source,c++]
----
lst.get_default_font_size()
----
a|
* Get the default font size of the label.
* Returns `float`.
a|
[source,c++]
----
lst.set_font_size(size)
----
a|
* Set the font size of the label.
* Compiler error if the styler does not have a font size property.
a|
[source,c++]
----
lst_set_relative_font_size(size)
----
a|
* Set the relative font size of the label.
* Compiler error if the styler does not have a font size property.

a|
[source,c++]
----
lst.get_font_color()
----
a|
* Get the font color of the label.
* Returns `{color}`.
* Returns the default if the styler does not have a font color property.
a|
[source,c++]
----
lst.set_font_color(color)
----
a|
* Set the font color of the label.
* Compiler error if the styler does not have a font color property.

a|
[source,c++]
----
lst.get_text_align()
----
a|
* Get the text alignment of the label.
* Returns `int`. See {text-align} for more info.
* Returns the default if the styler does not have a text alignment property.
a|
[source,c++]
----
lst.set_text_align(align)
----
a|
* Set the text alignment of the label. See {text-align} for more info.
* Compiler error if the styler does not have a text alignment property.

|===

'''

_Copyright (c) 2014-2024 Joel de Guzman. All rights reserved._
_Distributed under the {mit_license}_
