= Decks

include::../common.adoc[]

== Overview

The Deck is very similar to {Layers}. Elements are placed in the z-axis. But
unlike layers, only the selected element is active (top-most by default).

image::/layout/deck.svg[alt="deck", width=353px, role=center]

=== Semantics

* Everything listed in the {Layers_Semantics}, except 2 and 3.
* Only the active selected element element is drawn.
* Only the active selected element is given the chance to process UI control.

== deck

Create a deck composite with a fixed number of elements.

=== Notation

`N`:: The number of items

`+e1,...eN+`:: One or more child elements, instances of `Element`.

Elements `+e1,...eN+` are held in a `std::array<element_ptr, N>` managed by
the deck element.

=== Expressions

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
deck(e1, e2, e3... eN)
----
a|
* In addition to the semantics of Decks, returns instance of `Composite`.
|===

=== Example

[,c++]
----
deck(item1, item2, item3, item4)
----

NOTE: If the number of elements is not fixed, you can use an
`deck_composite` (see below).

=== Requirements

* In addition to the semantics of Deck, returns instance of `Composite`.

== deck_composite

Create a deck with an indeterminate (dynamic) number of elements.

=== Notation

`c`:: Instance of type `deck_composite`

The `deck_composite` is essentially a `std::vector<element_ptr>` that the
client uses to manage the composite's elements. The client is responsible for
the lifetime of the container, `c`. You use `deck_composite` just as you
would a `std::vector`, such as using `push_back` to add a child element.
Remember that the items are `element_ptr` instances.

=== Expression

[,c++]
----
deck_composite c;
----

=== Example

[,c++]
----
c.push_back(share(child));
----

NOTE: `share` turns an element object into an `element_ptr` held by
the `std::vector<element_ptr>` in `deck_composite`.

`deck_composite` is itself also an `element` and while it has ``std::vector``'s
interface, it can also be ``share``d like any element, which allows you to
build complex hierarchical structures.

'''

_Copyright (c) 2014-2024 Joel de Guzman. All rights reserved._
_Distributed under the {mit_license}_
