= Tiles

include::../common.adoc[]

== Overview

Tiles are the most useful layout elements. Tiles are used everywhere for
composing hierarchical elements in rows and columns, typical to all GUIs.
Tiles allow elements to fluidly adjust depending on available space. Tiles
compute the layout of its elements using the children elements' size
{limits}.

== Horizontal Tiles

image::/layout/htile.svg[alt="htile", width=462px, role=center]

Horizontal Tiles allow elements to fluidly adjust horizontally depending on
available space.

=== Semantics

* The elements are laid out in a single row, left to right, immediately next
to each other with no intervening space.
* The elements are positioned horizontally using the children's natural
{limits}.
* Horizontal space is allocated using this algorithm:
 .. Space is allocated for each child element following the child's natural
_minimum horizontal limit_.
 .. If the allocated space exceeds the sum of all children elements'
__minimum horizontal limit__s, the extra space is given to each
horizontally resizable element (`limits.min.x < limits.max.x`).
 .. The element's "stretchiness" determines how much extra space is given
to it according to the element's `stretch()` member function. A stretch
value of `1.0` is default. A stretchiness value of 2.0 means that the
element is able to stretch twice as much compared to its siblings.
Horizontally fixed-sized elements will not be stretched (element d in
the diagram). (Also see {Stretch-Elements}).
* The tile's _minimum vertical limit_ is computed as the maximum of the
children elements' __minimum vertical limit__s.
* The grid's _maximum vertical limit_ is computed as the minimum of the
children elements' __maximum vertical limit__s.
* The final computed minimum limit is clamped to ensure it is not greater
than the computed maximum limit. Likewise the computed maximum limit is
clamped to ensure it is not less than the computed minimum limit.
* The supplied (horizontal) and computed (vertical) coordinates may violate
the limits of its children elements.
 .. If the allocated size of a child element is lower than the element's
_minimum limits_ in either dimension, the element will be cropped.
 .. If a child element's _maximum limits_ in either dimension is exceeded,
the element will be aligned to the top-left.

== htile

Build a horizontal tile with a fixed number of elements.

=== Notation

`N`:: The number of items
`+e1,...eN+`:: One or more child elements, instances of `Element` (more below)

Elements `+e1,...eN+` are held in a `std::array<element_ptr, N>` managed by the
horizontal tile element.

=== Expressions

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
htile(e1,...eN)
----
a|
* In addition to the semantics of Horizontal Tiles, returns instance of
`Composite`.
|===

=== Example:

[,c++]
----
htile(item1, item2, item3, item4)
----

NOTE: If the number of elements is not fixed, you can use an
`htile_composite` (see below).

== htile_composite

Create a horizontal tile with an indeterminate (dynamic) number of elements.

=== Notation

`c`:: Instance of type `htile_composite`

The `htile_composite` is essentially a `std::vector<element_ptr>` that the
client uses to manage the composite's elements. The client is responsible for
the lifetime of the container, `c`. You use `htile_composite` just as you
would a `std::vector`, such as using `push_back` to add a child element. Just
remember that the items are `element_ptr` instances.

=== Expression

[,c++]
----
htile_composite c;
----

=== Example

[,c++]
----
c.push_back(share(child));
----

NOTE: `share` turns an element object into an `element_ptr` held by
the `std::vector<element_ptr>` in `htile_composite`.

`htile_composite` is itself also an `element` and while it has ``std::vector``'s
interface, it can also be ``share``d like any element, which allows you to
build complex hierarchical structures.

== Vertical Tiles

image::/layout/vtile.svg[alt="vtile", width=347px, role=center]

Vertical Tiles allow elements to fluidly adjust vertically depending on
available space.

=== Semantics

* The elements are laid out in a single column, top to bottom, immediately
next to each other with no intervening space.
* The elements are positioned vertically using the children's natural
{limits}.
* Vertical space is allocated using this algorithm:
 .. Space is allocated for each child element following the child's natural
_minimum vertical limit_.
 .. If the allocated space exceeds the sum of all children elements'
__minimum vertical limit__s, the extra space is given to each
vertically resizable element (`limits.min.y < limits.max.y`).
 .. The element's "stretchiness" determines how much extra space is given
to it according to the element's `stretch()` member function. A stretch
value of `1.0` is default. A stretchiness value of 2.0 means that the
element is able to stretch twice as much compared to its siblings.
Vertically fixed-sized elements will not be stretched (element b in the
diagram). (Also see {Stretch-Elements}).
* The tile's _minimum horizontal limit_ is computed as the maximum of the
children elements' __minimum horizontal limit__s.
* The grid's _maximum horizontal limit_ is computed as the minumum of the
children elements' __maximum horizontal limit__s.
* The final computed minimum limit is clamped to ensure it is not greater
than the computed maximum limit. Likewise the computed maximum limit is
clamped to ensure it is not less than the computed minimum limit.
* The supplied (vertical) and computed (horizontal) coordinates may violate
the limits of its children elements.
 .. If the allocated size of a child element is lower than the element's
_minimum limits_ in either dimension, the element will be cropped.
 .. If a child element's _maximum limits_ in either dimension is exceeded,
the element will be aligned to the top-left.

== vtile

Build a vertical tile with a fixed number of elements.

=== Notation

`N`:: The number of items
`+e1,...eN+`:: One or more child elements, instances of `Element`

Elements `+e1,...eN+` are held in a `std::array<element_ptr, N>` managed by the
vertical tile element.

=== Expressions

[cols="2,3", options="header"]
|===
| Expression | Semantics

a|
[source,c++]
----
vtile(e1,...eN)
----
a|
* In addition to the semantics of Vertical Tiles, returns instance of
`Composite`.
|===

=== Example

[,c++]
----
vtile(item1, item2, item3, item4)
----

NOTE: If the number of elements is not fixed, you can use an
`vtile_composite` (see below).

== vtile_composite

Create a vertical tile with an indeterminate (dynamic) number of elements.

=== Notation

`c`:: Instance of type `vtile_composite`

The `vtile_composite` is essentially a `std::vector<element_ptr>` that the
client uses to manage the composite's elements. The client is responsible for
the lifetime of the container, `c`. You can use `vtile_composite` in the same
way as a `std::vector`, such as using `push_back` to add a child element.
Just remember that the items are `element_ptr` instances.

=== Expression

[,c++]
----
vtile_composite c;
----

=== Example

[,c++]
----
c.push_back(share(child));
----

NOTE: `share` turns an element object into an `element_ptr` held by
the `std::vector<element_ptr>` in `vtile_composite`.

`vtile_composite` is itself also an `element` and while it has
``std::vector``'s interface, it can also be ``share``d like any element, which
allows you to build complex hierarchical structures.

'''

_Copyright (c) 2014-2024 Joel de Guzman. All rights reserved._
_Distributed under the {mit_license}_
