/*=============================================================================
   Copyright (c) 2016-2023 Joel de Guzman

   Distributed under the MIT License [ https://opensource.org/licenses/MIT ]
=============================================================================*/
#if !defined(ELEMENTS_ICON_IDS_JUNE_4_2016)
#define ELEMENTS_ICON_IDS_JUNE_4_2016

namespace cycfi::elements::icons
{
   // The glyphs of resources/fonts/elements_basic.ttf, built with Fontello
   // from resources/fonts/config.json. Code points are in the Unicode
   // private use area, laid out so an application's own icons never
   // collide with these:
   //
   //    0xe800 to 0xefff   Elements' icons (this enum)
   //    0xf000 to 0xf2ff   glyphs Fontello imports from other fonts, which
   //                       keep their codes (sliders, lightbulb, hand, menu,
   //                       unlink)
   //    0xf800 to 0xf8ff   an application's own icons
   //
   // To add icons, see the Icons page in the docs: start from config.json
   // so these keep their codes, give new glyphs codes from 0xf800, and
   // point ELEMENTS_ICON_FONT at the font Fontello builds.
   enum
   {
      left                          = 0xe800,
      right                         = 0xe801,
      up                            = 0xe802,
      down                          = 0xe803,
      left_dir                      = 0xe804,
      right_dir                     = 0xe805,
      up_dir                        = 0xe806,
      down_dir                      = 0xe807,
      left_circled                  = 0xe808,
      right_circled                 = 0xe809,
      up_circled                    = 0xe80a,
      down_circled                  = 0xe80b,
      left_open                     = 0xe80c,
      right_open                    = 0xe80d,
      up_open                       = 0xe80e,
      down_open                     = 0xe80f,
      angle_left                    = 0xe810,
      angle_right                   = 0xe811,
      angle_up                      = 0xe812,
      angle_down                    = 0xe813,
      angle_double_left             = 0xe814,
      angle_double_right            = 0xe815,
      angle_double_up               = 0xe816,
      angle_double_down             = 0xe817,
      angle_circled_left            = 0xe818,
      angle_circled_right           = 0xe819,
      angle_circled_up              = 0xe81a,
      angle_circled_down            = 0xe81b,
      exclamation                   = 0xe81c,
      block                         = 0xe81d,
      pencil                        = 0xe81e,
      pin                           = 0xe81f,
      resize_vertical               = 0xe820,
      resize_horizontal             = 0xe821,
      move                          = 0xe822,
      resize_full_alt               = 0xe823,
      resize_full                   = 0xe824,
      resize_small                  = 0xe825,
      magnifying_glass              = 0xe826,
      zoom_in                       = 0xe827,
      zoom_out                      = 0xe828,
      volume_off                    = 0xe829,
      volume_down                   = 0xe82a,
      volume_up                     = 0xe82b,
      cw                            = 0xe82c,
      ccw                           = 0xe82d,
      cycle                         = 0xe82e,
      level_up                      = 0xe82f,
      level_down                    = 0xe830,
      shuffle                       = 0xe831,
      exchange                      = 0xe832,
      power                         = 0xe833,
      play                          = 0xe834,
      stop                          = 0xe835,
      pause                         = 0xe836,
      record                        = 0xe837,
      to_end                        = 0xe838,
      to_start                      = 0xe839,
      fast_forward                  = 0xe83a,
      fast_backward                 = 0xe83b,
      wrench                        = 0xe83c,
      trash                         = 0xe83d,
      trash_empty                   = 0xe83e,
      ok                            = 0xe83f,
      cancel                        = 0xe840,
      plus                          = 0xe841,
      minus                         = 0xe842,
      cog                           = 0xe843,
      doc                           = 0xe844,
      docs                          = 0xe845,
      lock_open                     = 0xe846,
      lock                          = 0xe847,
      sliders                       = 0xf1de,
      floppy                        = 0xe848,
      attention                     = 0xe849,
      info                          = 0xe84a,
      error                         = 0xe84b,
      lightbulb                     = 0xf0eb,
      mixer                         = 0xf1de,
      hand                          = 0xf256,
      question                      = 0xe84c,
      menu                          = 0xf0c9,
      link                          = 0xe84e,
      unlink                        = 0xf127,
      folder_empty                  = 61716,
      folder_open_empty             = 61717,

      // Drawn for Elements, not from a Fontello set: a window with a
      // smaller one beside it and a diagonal arrow, for the buttons that
      // scale a view up and down.
      expand                        = 0xe84f,
      shrink                        = 0xe850,

      // Added 2026-10-06 from Font Awesome 4.7, through Fontello.
      file_text                     = 0xe851,
      file_image                    = 0xe852,
      file_audio                    = 0xe853,
      file_code                     = 0xe854,
      file_archive                  = 0xe855,
      file_pdf                      = 0xe856,
      upload                        = 0xe857,
      download                      = 0xe858,
      export_file                   = 0xe859,
      import                        = 0xe85a,
      archive                       = 0xe85b,
      database                      = 0xe85c,
      hdd                           = 0xe85d,
      paste                         = 0xe85e,
      cut                           = 0xe85f,
      duplicate                     = 0xe860,
      edit                          = 0xe861,
      eraser                        = 0xe862,
      crop                          = 0xe863,
      paint_brush                   = 0xe864,
      eyedropper                    = 0xe865,
      text_height                   = 0xe866,
      text_width                    = 0xe867,
      bold                          = 0xe868,
      italic                        = 0xe869,
      underline                     = 0xe86a,
      align_left                    = 0xe86b,
      align_center                  = 0xe86c,
      align_right                   = 0xe86d,
      align_justify                 = 0xe86e,
      indent                        = 0xe86f,
      outdent                       = 0xe870,
      list_ul                       = 0xe871,
      list_ol                       = 0xe872,
      table                         = 0xe873,
      font                          = 0xe874,
      paragraph                     = 0xe875,
      code                          = 0xe876,
      eye                           = 0xe877,
      eye_off                       = 0xe878,
      filter                        = 0xe879,
      list                          = 0xe87a,
      grid                          = 0xe87b,
      grid_large                    = 0xe87c,
      window                        = 0xe87d,
      window_restore                = 0xe87e,
      window_minimize               = 0xe87f,
      window_close                  = 0xe880,
      columns                       = 0xe881,
      sort                          = 0xe882,
      sort_up                       = 0xe883,
      sort_down                     = 0xe884,
      sitemap                       = 0xe885,
      check_circle                  = 0xe886,
      check_circle_o                = 0xe887,
      times_circle                  = 0xe888,
      warning_circle                = 0xe889,
      clock                         = 0xe88a,
      hourglass                     = 0xe88b,
      spinner                       = 0xe88c,
      circle_notch                  = 0xe88d,
      star                          = 0xe88e,
      star_empty                    = 0xe88f,
      star_half                     = 0xe890,
      heart                         = 0xe891,
      heart_empty                   = 0xe892,
      bookmark                      = 0xe893,
      bookmark_empty                = 0xe894,
      tag                           = 0xe895,
      tags                          = 0xe896,
      flag                          = 0xe897,
      flag_empty                    = 0xe898,
      thumbs_up                     = 0xe899,
      thumbs_down                   = 0xe89a,
      bug                           = 0xe89b,
      shield                        = 0xe89c,
      battery_full                  = 0xe89d,
      battery_half                  = 0xe89e,
      battery_empty                 = 0xe89f,
      home                          = 0xe8a0,
      dots                          = 0xe8a1,
      dots_vertical                 = 0xe8a2,
      caret_square_left             = 0xe8a3,
      caret_square_right            = 0xe8a4,
      long_arrow_left               = 0xe8a5,
      long_arrow_right              = 0xe8a6,
      long_arrow_up                 = 0xe8a7,
      long_arrow_down               = 0xe8a8,
      external_link_square          = 0xe8a9,
      reply                         = 0xe8aa,
      share                         = 0xe8ab,
      retweet                       = 0xe8ac,
      location                      = 0xe8ad,
      compass                       = 0xe8ae,
      map                           = 0xe8af,
      crosshairs                    = 0xe8b0,
      user                          = 0xe8b1,
      users                         = 0xe8b2,
      user_plus                     = 0xe8b3,
      user_circle                   = 0xe8b4,
      calendar                      = 0xe8b5,
      calendar_check                = 0xe8b6,
      bell                          = 0xe8b7,
      bell_off                      = 0xe8b8,
      help                          = 0xe8b9,
      keyboard                      = 0xe8ba,
      mouse                         = 0xe8bb,
      hand_pointer                  = 0xe8bc,
      print                         = 0xe8bd,
      camera                        = 0xe8be,
      video                         = 0xe8bf,
      picture                       = 0xe8c0,
      globe                         = 0xe8c1,
      cloud                         = 0xe8c2,
      cloud_upload                  = 0xe8c3,
      cloud_download                = 0xe8c4,
      bluetooth                     = 0xe8c5,
      usb                           = 0xe8c6,
      wifi                          = 0xe8c7,
      plug                          = 0xe8c8,
      bolt                          = 0xe8c9,
      magic                         = 0xe8ca,
      toggle_on                     = 0xe8cb,
      toggle_off                    = 0xe8cc,
      key                           = 0xe8cd,
      envelope                      = 0xe8ce,
      comment                       = 0xe8cf,
      comments                      = 0xe8d0,
      paperclip                     = 0xe8d1,
      book                          = 0xe8d2,
      briefcase                     = 0xe8d3,
      shopping_cart                 = 0xe8d4,
      credit_card                   = 0xe8d5,
      gift                          = 0xe8d6,
      trophy                        = 0xe8d7,
      desktop                       = 0xe8d8,
      laptop                        = 0xe8d9,
      tablet                        = 0xe8da,
      mobile                        = 0xe8db,
      server                        = 0xe8dc,
      microchip                     = 0xe8dd,
      terminal                      = 0xe8de,
      cogs                          = 0xe8df,
      puzzle                        = 0xe8e0,
      rocket                        = 0xe8e1,
      flask                         = 0xe8e2,
      gamepad                       = 0xe8e3,
      television                    = 0xe8e4,
      calculator                    = 0xe8e5,
      language                      = 0xe8e6,
      sun                           = 0xe8e7,
      moon                          = 0xe8e8,
      history                       = 0xe8e9,
      recycle                       = 0xe8ea,
      sign_out                      = 0xe8eb,
      qrcode                        = 0xe8ec,
      barcode                       = 0xe8ed,
      chart_bar                     = 0xe8ee,
      chart_line                    = 0xe8ef,
      chart_pie                     = 0xe8f0,
      chart_area                    = 0xe8f1,
      music                         = 0xe8f2,
      headphones                    = 0xe8f3,
      microphone                    = 0xe8f4,
      microphone_off                = 0xe8f5,
      eject                         = 0xe8f6,
      signal                        = 0xe8f7,
      tachometer                    = 0xe8f8,
      dot_circled                   = 0xe8f9,
      circle_empty                  = 0xe8fa,
      bullseye                      = 0xe8fb,
      step_backward                 = 0xe8fc,
      step_forward                  = 0xe8fd,
      circle                        = 0xe8fe,
      square                        = 0xe8ff,
      adjust                        = 0xe900,
      stop_circle                   = 0xe901,
      play_circle                   = 0xe902,
      pause_circle                  = 0xe903,
   };
}

#endif
