/*=============================================================================
   Copyright (c) 2016-2020 Joel de Guzman

   Distributed under the MIT License [ https://opensource.org/licenses/MIT ]
=============================================================================*/
#if !defined(ELEMENTS_ICON_IDS_JUNE_4_2016)
#define ELEMENTS_ICON_IDS_JUNE_4_2016

namespace cycfi { namespace elements { namespace icons
{
   enum
   {
      left                          = 0xe800,
      right                         = 0xe801,
      up                            = 0xe802,
      down                          = 0xe803,
      left_dir                      = 0xe804,
      right_dir                     = 0xe805,
      up_dir                        = 0xe806,
      down_dir                      = 0xe807,
      left_circled                  = 0xe808,
      right_circled                 = 0xe809,
      up_circled                    = 0xe80a,
      down_circled                  = 0xe80b,
      left_open                     = 0xe80c,
      right_open                    = 0xe80d,
      up_open                       = 0xe80e,
      down_open                     = 0xe80f,
      angle_left                    = 0xe810,
      angle_right                   = 0xe811,
      angle_up                      = 0xe812,
      angle_down                    = 0xe813,
      angle_double_left             = 0xe814,
      angle_double_right            = 0xe815,
      angle_double_up               = 0xe816,
      angle_double_down             = 0xe817,
      angle_circled_left            = 0xe818,
      angle_circled_right           = 0xe819,
      angle_circled_up              = 0xe81a,
      angle_circled_down            = 0xe81b,
      exclamation                   = 0xe81c,
      block                         = 0xe81d,
      pencil                        = 0xe81e,
      pin                           = 0xe81f,
      resize_vertical               = 0xe820,
      resize_horizontal             = 0xe821,
      move                          = 0xe822,
      resize_full_alt               = 0xe823,
      resize_full                   = 0xe824,
      resize_small                  = 0xe825,
      magnifying_glass              = 0xe826,
      zoom_in                       = 0xe827,
      zoom_out                      = 0xe828,
      volume_off                    = 0xe829,
      volume_down                   = 0xe82a,
      volume_up                     = 0xe82b,
      cw                            = 0xe82c,
      ccw                           = 0xe82d,
      cycle                         = 0xe82e,
      level_up                      = 0xe82f,
      level_down                    = 0xe830,
      shuffle                       = 0xe831,
      exchange                      = 0xe832,
      power                         = 0xe833,
      play                          = 0xe834,
      stop                          = 0xe835,
      pause                         = 0xe836,
      record                        = 0xe837,
      to_end                        = 0xe838,
      to_start                      = 0xe839,
      fast_forward                  = 0xe83a,
      fast_backward                 = 0xe83b,
      wrench                        = 0xe83c,
      trash                         = 0xe83d,
      trash_empty                   = 0xe83e,
      ok                            = 0xe83f,
      cancel                        = 0xe840,
      plus                          = 0xe841,
      minus                         = 0xe842,
      cog                           = 0xe843,
      doc                           = 0xe844,
      docs                          = 0xe845,
      lock_open                     = 0xe846,
      lock                          = 0xe847,
      sliders                       = 0xf1de,
      floppy                        = 0xe848,
      attention                     = 0xe849,
      info                          = 0xe84a,
      error                         = 0xe84b,
      lightbulb                     = 0xf0eb,
      mixer                         = 0xf1de,
      hand                          = 0xf256,
      question                      = 0xe84c,
      menu                          = 0xf0c9
   };
}}}

#endif
